In [ ]:
#함수

def my_func(para1) :
  print(para1)

In [ ]:
my_func("나는 서울여대생이다.")

나는 서울여대생이다.


In [ ]:
def my_func1(name) :
  print(name, "서울여대생이다.")

In [ ]:
my_func1("줄리아")

줄리아 서울여대생이다.


In [ ]:
def my_func2(name1, name2, name3) :
  print(name1, name2, name3, "서울여대생이다")

In [ ]:
my_func2("앤디", "줄리아", "케이트")

앤디 줄리아 케이트 서울여대생이다


#함수는 값을 return할 수 있고, 또 안해도 된다.

- return이 없는 경우

In [ ]:
def my_func(x, y) :
  print(x, y)

In [ ]:
my_func(10, 1000)

10 1000


- return이 있는 경우

In [ ]:
def my_func3(x, y) :
  z = x + y
  return z


In [ ]:
my_func3(10, 100)

110

- (x + y) * 2z 라는 함수

In [ ]:
def my_func(x, y, z) :
  return (x + y) * 2 * z

In [ ]:
my_func(2, 3, 4)

40

- return이 있는 경우에 변수에 값을 다시 할당할 수 있음

In [ ]:
#ret(return) 리턴값을 다시 사용가능
ret = my_func3(10, 100)
ret * 11

1210

#import csv file

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving bicycle.csv to bicycle.csv


In [ ]:
data = pd.read_csv("bicycle.csv", encoding = "CP949")

In [ ]:
data.head()

자전거번호              대여일시  대여소번호               대여소명  대여거치대  \
0  SPB-23220   2019-11-01 8:48    646  장한평역 1번출구 (국민은행앞)    3.0   
1  SPB-16216   2019-11-04 8:38    646  장한평역 1번출구 (국민은행앞)    2.0   
2  SPB-21097   2019-11-04 8:46    646  장한평역 1번출구 (국민은행앞)    1.0   
3  SPB-22292   2019-11-05 8:34    646  장한평역 1번출구 (국민은행앞)    1.0   
4  SPB-07935  2019-11-05 12:29    512        뚝섬역 1번 출구 옆   11.0   

               반납일시  반납대여소번호 반납대여소명  반납거치대  이용시간    이용거리  
0   2019-11-01 9:01        3   중랑센터    7.0  12.0  1100.0  
1   2019-11-04 8:56        3   중랑센터    2.0   7.0  1420.0  
2   2019-11-04 8:57        3   중랑센터    7.0  10.0     NaN  
3   2019-11-05 8:45        3   중랑센터    NaN  10.0  1380.0  
4  2019-11-05 12:39        3   중랑센터    7.0  10.0  1650.0

## 패키지 모듈 그리고 함수

- 함수들이 뭉쳐진 하나의 .py 파일 안에 이루어진 것을 모듈이라고 함
- 여러개의 모듈을 그룹화하면 패키지가 됨
- 패키지느 ㄴ종종 라이브러리라고도 함

## moodule import 하기

- import : python의 유용한 기능
           다른 사람이 이미 만들어 놓은 좋은 모듈을 우리가 쉽게 가져다 쓸 수 있음

- import 하는 방법
  - .py(파이썬 확장자)로 된 파일을 우리는 모듈이라고 함
  - import 구문을 통해 해당 파일을 불러올 수 있음

In [ ]:
import pandas #pandas라는 모듈을 우리가 불러오겠다는 의미. colab에서는 이미 설치는 다 되어있음 cf. 설치는 install

- 이미 colab에서는 유명한 모듈은 설치되어 있는 상태여서 우리가 따로 설치할 필요가 없다.

### 패키지에서 importgkrl

- 패키지는 모듈의 그룹
  - (예시) 파일1, 파일2, 파일3 등을 하나의 "팬더" 폴더 안에 있다고 가정
  - 팬더 = 패키지
  - 파일1, 파일2, 파일3은 각각의 모듈이 된다.


- (예시)
  - 팬더라는 패키지 안에 파일1(module)을 가져오려고 함
  - from 팬더 import 파일1

In [ ]:
from pandas import DataFrame

# pandas 라는 패키지 안에 DataFrame이라는 module을 불러옴

### 별칭 지어주기 alias

- 예시
  - pandas 라는 패키지 이름이 너무 길어서 약어로 줄임
  - 별칭을 지어주는데 이때 as를 붙여줌

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

### 향후 자주 사용할 패키지, 모듈 소개

- import numpy as np
  - numpy : 과학계산을 위한 패키지

- import pandas as pd
  - pandas : 데이터 분석 시 가장 많이 쓰는 패키지


- import matplotlib.pyplot as plt

  - matplotlib : 시각화하는 패키지


- import seaborn as sns
  - seaborn : 시각화 패키지

# 1. Pandas 데이터 구조

In [ ]:
import pandas as pd

In [ ]:
series1 = pd.Series(["Bus", "Train", "KTX", "Taxi"], index = ["0", "1", "2", "3"])
#column vector를(Python에서는 list 형식) Series라고 함. pandas에서 인덱스 항시 필요

In [ ]:
series1

0      Bus
1    Train
2      KTX
3     Taxi
dtype: object

### Series

   - 가장 간단한 1차원의 자료 구조
   - Series 는 배열/리스트 같은 일련의 시퀀스 데이터를 받아들이고 있음
   - 별도의 인덱스 레이블을 저장하지 않는다면, 자동적으로 0부터 시작되는 디폴트 정수 인덱스가 사용된다.

In [ ]:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
type(data)

list

In [ ]:
pd.Series(data)
#리스트를 시리즈로 바꿈
#리스트는 항아리. 어떤 데이터를 정렬시키는 것(using index)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [ ]:
series2 = pd.Series(data)

In [ ]:
type(series2)

pandas.core.series.Series

pd 1. series 2. dataframe

#### DataFrame

- 2차원의 구조 (여러개 쌓고쌓을 수 있음. 수업에선 x)
- 행과 열로 되어있는 테이블 데이터

In [ ]:
import pandas as pd

In [ ]:
df_data = {
    "Year" : [2020, 2021, 2022, 2023],
    "GDP growth" : [-0.9, 1.3, 1.5, 1.1],
    "inflation rate" : [0.2, 1.0, 6.0, 3.4]
}

In [ ]:
df_data

{'Year': [2020, 2021, 2022, 2023],
 'GDP growth': [-0.9, 1.3, 1.5, 1.1],
 'inflation rate': [0.2, 1.0, 6.0, 3.4]}

In [ ]:
type(df_data)

dict

In [ ]:
df = pd.DataFrame(df_data) #2차원의 구조

In [ ]:
df

Year  GDP growth  inflation rate
0  2020        -0.9             0.2
1  2021         1.3             1.0
2  2022         1.5             6.0
3  2023         1.1             3.4

- 데이터 접근

In [ ]:
df["Year"]

0    2020
1    2021
2    2022
3    2023
Name: Year, dtype: int64

In [ ]:
df.Year

0    2020
1    2021
2    2022
3    2023
Name: Year, dtype: int64

In [ ]:
df["GDP growth"]

0   -0.9
1    1.3
2    1.5
3    1.1
Name: GDP growth, dtype: float64

In [ ]:
df[df["Year"]>2021]

Year  GDP growth  inflation rate
2  2022         1.5             6.0
3  2023         1.1             3.4

In [ ]:
df[df["Year"]>=2021]

Year  GDP growth  inflation rate
1  2021         1.3             1.0
2  2022         1.5             6.0
3  2023         1.1             3.4

In [ ]:
df[df["Year"]==2020]

Year  GDP growth  inflation rate
0  2020        -0.9             0.2

In [ ]:
df[df["Year"]<=2022]

Year  GDP growth  inflation rate
0  2020        -0.9             0.2
1  2021         1.3             1.0
2  2022         1.5             6.0

In [ ]:
sum_GDP = df["GDP growth"].sum()

In [ ]:
sum_GDP

3.0

In [ ]:
sum_inflation = df["inflation rate"].sum()

In [ ]:
sum_inflation

10.6

In [ ]:
avg_GDP = df["GDP growth"].mean()

In [ ]:
avg_GDP

0.75

In [ ]:
avg_infla = df["inflation rate"].mean()

In [ ]:
avg_infla

2.65

In [ ]:
df.describe()

Year  GDP growth  inflation rate
count     4.000000    4.000000        4.000000
mean   2021.500000    0.750000        2.650000
std       1.290994    1.112055        2.614702
min    2020.000000   -0.900000        0.200000
25%    2020.750000    0.600000        0.800000
50%    2021.500000    1.200000        2.200000
75%    2022.250000    1.350000        4.050000
max    2023.000000    1.500000        6.000000

# 2. Numpy

- 과학계산을 위한 라이브러리
- 다차원의 배열을 처리하는 데 여러 유용한 기능을 가지고 있음
- 벡터, 행렬 연산에 있어서 매우 편리함
   - numpy는 기본적으로 array(행렬개념)라는 단위로 데이터를 관리 및 연산을 수행

In [ ]:
import numpy as np

In [ ]:
data = [10, 20, 30, 40, 50]

In [ ]:
type(data)

list

In [ ]:
array1 = np.array(data)

In [ ]:
array1

array([10, 20, 30, 40, 50])

In [ ]:
type(array1)

numpy.ndarray

In [ ]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(array2)

numpy.ndarray

In [ ]:
array2.shape

(3, 3)

- **np.shape**


  - numpy에서 해당하는 array차원을 알 수 있음
  - shape : 몇개의 데이터가 존재, 몇 차원으로 데이터가 존재하는 지를 알려줌


  -(예시)
   - array.shape 결과가 (5, )
    - 1차원의 데이터, 총 5개의 크기를 가짐

- array.shape 결과가 (4, 3)
     - 2차원의 데이터, 4x3을 가지는 array

- numpy 에서 array 정의할 때 사용되는 함수

  - np.zeros()
  - np.ones()
  - np.arange()

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.array([[np.zeros(2)], [np.zeros(2)], [np.zeros(2)]])

array([[[0., 0.]],

       [[0., 0.]],

       [[0., 0.]]])

In [ ]:
np.array([[np.ones(4)], [np.ones(4)]])

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

- ** np.arange**

  - 인자로 받는 값 만큼 1씩 증가하는 1차원의 array 생성

In [ ]:
np.arange(3, 8)

array([3, 4, 5, 6, 7])

In [ ]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10) #인덱스가 0부터 시작하기 때문에

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10)*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.arange(1, 5, 0.8)

array([1. , 1.8, 2.6, 3.4, 4.2])

- array 행렬 덧셈과 뺄셈

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])

In [ ]:
arr1 + arr2

array([[11, 22, 33],
       [44, 55, 66]])

In [ ]:
arr2 - arr1

array([[ 9, 18, 27],
       [36, 45, 54]])

In [ ]:
arr1 * arr2
#point wise방식으로 곱해짐. 행렬의 곱셈으로 안됨. 나눗셈도 마찬가지

array([[ 10,  40,  90],
       [160, 250, 360]])

In [ ]:
arr1/arr2

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

- np.random.randn

#meaning they pick randomly from the normal distribution
  - mean = 0, std(standard deviation) = 1 을 가지는 정규분포


In [ ]:
data = np.random.randn(6, 3)

In [ ]:
data.shape

(6, 3)

In [ ]:
data

array([[-1.27931672,  0.04830827,  1.35442445],
       [ 0.58775702, -1.99631469, -0.83162326],
       [-0.23463907, -2.10949531,  1.28052033],
       [-1.55535738,  0.82493894,  1.1506886 ],
       [-1.55746799,  1.08792009, -1.41987096],
       [-2.23398801,  0.01823886,  0.76736019]])

In [ ]:
#negative를 없애자 -> absolute로 만들자!
np.abs(data)

array([[1.27931672, 0.04830827, 1.35442445],
       [0.58775702, 1.99631469, 0.83162326],
       [0.23463907, 2.10949531, 1.28052033],
       [1.55535738, 0.82493894, 1.1506886 ],
       [1.55746799, 1.08792009, 1.41987096],
       [2.23398801, 0.01823886, 0.76736019]])

In [ ]:
#square root를 취하자! 음수만 not a number nan
np.sqrt(data)

<ipython-input-116-1b7eb5adda0d>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(data)


array([[       nan, 0.21979143, 1.16379743],
       [0.76665313,        nan,        nan],
       [       nan,        nan, 1.13160078],
       [       nan, 0.9082615 , 1.07270154],
       [       nan, 1.04303408,        nan],
       [       nan, 0.13505131, 0.87599098]])

In [ ]:
np.exp(data) #지수함수 e(자연상수)로 변환

array([[0.27822734, 1.04949414, 3.87453032],
       [1.79994664, 0.13583496, 0.43534204],
       [0.79085624, 0.12129917, 3.59851165],
       [0.21111392, 2.28174145, 3.1603684 ],
       [0.21066881, 2.96809428, 0.24174521],
       [0.10710046, 1.0184062 , 2.1540724 ]])